version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    build: 
      context: .
      dockerfile: nginx.dockerfile
    links:
    - aspnetcoreapp1:aspnetcoreapp1
    - aspnetcoreapp2:aspnetcoreapp2
    ports:
    - "8000:8000"
    networks:
        - aspnetcoreapp-network

  aspnetcoreapp1:
    container_name: 'aspnetcoreapp1'
    image: 'aspnetcoreapp'
    environment:
    - Database=1
    build:
      context: .
      dockerfile: netcore.dockerfile
    ports:
     - "5000"
    networks:
      - aspnetcoreapp-network

  aspnetcoreapp2:
    container_name: 'aspnetcoreapp2'
    image: 'aspnetcoreapp'
    environment:
    - Database=2
    build:
      context: .
      dockerfile: netcore.dockerfile
    ports:
     - "5000"
    networks:
      - aspnetcoreapp-network

  postgres:
    container_name: 'postgres'
    image: postgres
    ports:
     - "5432:5432"
    volumes:
     - db:/var/lib/postgresql/data
    networks:
      - aspnetcoreapp-network

  mongo:
    container_name: 'mongo'
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - mongodb:/data/db
    networks:
      - aspnetcoreapp-network

  redis:
    container_name: redis
    image: redis
    ports:
     - "6379:6379"
    networks:
     - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge

volumes:
  db:
    external: true
  mongodb:
    external: true
