version: '2'

services:

  web:
    container_name: 'aspnetcoreapp'
    image: 'aspnetcoreapp'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5000:5000"
    networks:
      - aspnetcoreapp-network

  postgres:
    container_name: 'postgres'
    image: postgres
    ports:
     - "5432:5432"
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge
